# Generated by Django 3.2 on 2025-03-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fake', models.BooleanField()),
                ('confidence_score', models.FloatField()),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='heatmaps/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deepfake_app.videoupload')),
            ],
        ),
    ]
