# Generated by Django 5.1.7 on 2025-04-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepfake_app', '0003_deepfakeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepfakeimage',
            name='grad_cam_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
