# Generated by Django 5.1.7 on 2025-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepfake_app', '0004_deepfakeimage_grad_cam_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepfakeimage',
            name='eye_reflection_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='lbp_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='skin_texture_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
