# Generated by Django 5.1.7 on 2026-02-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepfake_app', '0005_deepfakeimage_eye_reflection_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deepfakeimage',
            name='eye_reflection_features',
        ),
        migrations.RemoveField(
            model_name='deepfakeimage',
            name='grad_cam_path',
        ),
        migrations.RemoveField(
            model_name='deepfakeimage',
            name='lbp_features',
        ),
        migrations.RemoveField(
            model_name='deepfakeimage',
            name='skin_texture_features',
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='bar_plot_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='decision_source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='gradcam_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='radar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='watermark_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deepfakeimage',
            name='watermark_prob',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
